### ISSUE TITLE
githudd: /usr/local/var/run/githudd.pid: openFd: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by gumho** [gbataille/gitHUD#21]
Getting the following error when running `githud bash` after installing on a Mac with brew:

```
githudd: /usr/local/var/run/githudd.pid: openFd: does not exist (No such file or directory)
```

**Comment by gumho** [comment]
Fixed it by doing `mkdir  /usr/local/var/run`. Looks like brew install doesn't create this directory by default.

**Comment by gbataille** [comment]
Interesting. I assumed this was a Mac specific directory because on Mac, by default, you can't write in `/var/run`

I don't know what created that folder for me.
What you can do rather than create the folder is to change the configuration telling where the `pid` and `socket` files are going.

What you are pointing out though is that this folder is not a smart default. But I don't know what is then. Such things usually go in `/var/run` but this is owned by root on Mac.

maybe I should use `$TMPDIR`. I'll have a look. I don't know where this points to on linux

**Comment by gbataille** [comment]
Ok so here is my plan:

You can still specify the `pid` and `socket` path in your config but if you don't (and that's going to be the default), I'll use that
```haskell
getTemporaryDirectory :: IO FilePath Source
```
where the doc says

> Returns the current directory for temporary files.
>
> On Unix, getTemporaryDirectory returns the value of the TMPDIR environment variable or "/tmp" if the variable isn't defined. On Windows, the function checks for the existence of environment variables in the following order and uses the first path found:
>
> TMP environment variable.
> TEMP environment variable.
> USERPROFILE environment variable.
> The Windows directory
> The operation may fail with:
>
> UnsupportedOperation The operating system has no notion of temporary directory.
> The function doesn't verify whether the path exists.
```

That's actually a much better, more standard way to proceed
