### ISSUE TITLE
run_fetcher_daemon option not taken into account

### ISSUE THREAD

**Issue by gbataille** [gbataille/gitHUD#28]
when `run_fetcher_daemon=False` I expect the `githudd` daemon not to start. It does.

From a brief look in the code, this config does not seem to be a used anywhere :/

**Comment by voidus** [comment]
For security reasons, I have an additional confirmation popup on ssh key usage so that I notice when background tasks open an ssh connection. This issue makes using this a big problem.

It's also a bit frustrating since the readme says it's disabled by default, while it is actually unconditionally enabled.
I'll see if I can have a look tomorrow.

**Comment by gbataille** [comment]
damn, when I saw the notification, I thought you opened the issue yourself. I had no recollection of that.

I have not done any haskell in a few years, but let me see if I can do something.
