### ISSUE TITLE
ZSH prompt does not update after initial sourcing

### ISSUE THREAD

**Issue by superstrong** [gbataille/gitHUD#32]
Excited to get this fully set up!

I've followed the instructions for installing with ZSH with these steps:
* `brew tap gbataille/homebrew-gba`
*  `brew install githud`

Added this to my `~/.zshrc`:
* `export PROMPT="%{$fg_bold[white]%}%T%{$reset_color%}%{$fg[cyan]%} %n%{$reset_color%} $(/usr/local/bin/githud zsh) $ "`

I've confirmed there's an executable at `/usr/local/bin/githud`.

If I manually run `/usr/local/bin/githud zdh` it echoes the correct status, but then returns to the old prompt. Here's an example, where I'm actually on the branch `core-dev` but it still shows me on `frame-success-master`:

```
23:35 robbie ᚴ [frame-success-master] $ /usr/local/bin/githud zsh
%{%}ᚴ [%{%}core-dev%{%}]
23:35 robbie ᚴ [frame-success-master] $
```

**Am I missing something in getting it to refresh every time the prompt loads?**

**Comment by superstrong** [comment]
In case it's related, I am also still trying to figure out how to get ZSH to source ~/.zshrc` automatically when I open a new window. (This is a relatively new computer I'm still setting up.)

**Comment by gbataille** [comment]
Hey @superstrong 

Found it. the `README` has an error. If you define `PROMPT` using double quotes (`"`), then the subcommand `$(...githud zsh)` is executed _at the definition of `PROMPT`_.

You can check that by doing `echo $PROMPT`. I'm pretty user it'll show the "hardcoded" prompt rather than having kept the subcommand call to `githud`.

To have the `PROMPT` not evaluated at variable definition, but only when rendering the prompt, you need to surround the `PROMPT` definition with single quotes '`'

Let me know if that does it. I'll change the `README` accordingly

**Comment by superstrong** [comment]
Close! I needed to do two things:
* Execute `setopt PROMPT_SUBST` [as described here](https://superuser.com/questions/142099/get-function-into-ps1-zsh)
* Wrap the PROMPT definition in single quotes instead of double quotes as you suggested

Thanks!

**Comment by superstrong** [comment]
Opened https://github.com/gbataille/gitHUD/pull/33. Thanks again for this project!
